### ISSUE TITLE
Tool crushes if the vm name is wrong

### ISSUE THREAD

**Issue by ebenezergraham** [GoogleCloudPlatform/gce-rescue#22]
Gracefully handle erronous VMs and allow the user correct the name or even better suggest the correct name

```
gce-rescue --zone europe-central2-a --name test
Traceback (most recent call last):
  File "/home/username/.local/bin/gce-rescue", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.9/site-packages/gce_rescue/bin/rescue.py", line 44, in main
    vm = Instance(test_mode=False, **parse_kwargs)
  File "<string>", line 12, in __init__
  File "/home/username/.local/lib/python3.9/site-packages/gce_rescue/gce.py", line 116, in __post_init__
    self.compute = check.compute
  File "/home/username/.local/lib/python3.9/site-packages/gce_rescue/tasks/pre_validations.py", line 52, in compute
    return self._authentication()
  File "/home/username/.local/lib/python3.9/site-packages/gce_rescue/tasks/pre_validations.py", line 39, in _authentication
    return authenticate_check(
  File "/home/username/.local/lib/python3.9/site-packages/gce_rescue/tasks/validations/authentication.py", line 66, in authenticate_check
    request.execute()
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
```

**Comment by halleysouza** [comment]
Thanks @ebenezergraham 

For now I think we can better handle this exception here:

https://github.com/GoogleCloudPlatform/gce-rescue/blob/bf17bf8465cd191010da56c19e23a00827e3a209/gce_rescue/gce.py#L41

I like the idea of suggestions, but I believe the suggestion should be only when user parse the wrong zone.

Perhaps name-matching the VM name can be too risk, inducing the users to make mistakes, as some company's VM nomenclature can cause the names to be very similar (ie: p = production, d = dev, etc)

Let me know what you think
