### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for gce-rescue

### ISSUE THREAD

**Issue by bskou57** [GoogleCloudPlatform/gce-rescue#44]
Hi

Can you please advise on below error message ?

importlib.metadata.PackageNotFoundError: No package metadata was found for gce-rescue
cq032_t1@cloudshell:~ (dbg-clearstream-simu-fe9d0e70)$ gce-rescue -z europe-west3-a -
Traceback (most recent call last):
  File "/home/cq032_t1/.local/bin/gce-rescue", line 33, in <module>
    sys.exit(load_entry_point('gce-rescue==0.4b0', 'console_scripts', 'gce-rescue')()
  File "/home/cq032_t1/.local/bin/gce-rescue", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distributio
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gce-rescue

Thanks for your help

**Comment by halleysouza** [comment]
Can you pls share more info ? 

I can see you are running from Cloudshell, but how did you install gce-rescue ?

**Comment by gokulr94** [comment]
This appears to be an installation issue with V1. We recommend trying GCE Rescue V2 (currently in beta) which has improved packaging:

  pip uninstall gce-rescue
  pip install git+https://github.com/GoogleCloudPlatform/gce-rescue.git@v2-beta

  **V2 Documentation:** https://github.com/GoogleCloudPlatform/gce-rescue/blob/v2-beta/gce_rescue_v2/README.md

  Note: V2 is in active beta development. Please reopen if issue persists with V2.
